### PR TITLE
Create Jump_search.cpp

### PR DESCRIPTION
**Pull request by Ash-KODES**
jump search algorithm added
hackktober 2021

### CODE REVIEW

**Comment by Ash-KODES** [comment]
@piyush-kash please revie and merge my code:)
thankyou!

**Comment by piyush-kash** [comment]
Star this repo 🌟

**Comment by Ash-KODES** [comment]
> Star this repo star2

ya sure!
can you please add the tag hacktober accepted

**Comment by piyush-kash** [comment]
no need the whole repo is already tagged

**Pull request merged**
